mathalea/mathaleaV3

src/components/InputListeExercices.svelte

fix: problème de casse dans un import

---

src/exercices/beta/betaTestFraction.js
src/interactif/mathLive.js
src/modules/gestionInteractif.js
src/modules/interactif/questionMathLive.js
src/modules/outils.js
src/modules/outilsMathjs.js
src/modulesv2/gestionInteractif.js
src/modulesv2/outils.js
src/modulesv2/questionMathLive.js

Faudra trouver une solution pour node...

fix: import ComuteEngine et Decimal.

---

src/components/header2/Searchbar.svelte

Multi recherche + mise en gras du match

Maxime autocomplete4

---

src/components/header2/Searchbar.svelte

* correction pour firefox
* nettoyage code inutile + ajouts commentaires
(testé FF chrome edge)

fix : searchbar

---

src/components/Start.svelte
src/components/sidebar/EntreeListeExos.svelte

Ajout d'ne entrée Nouveauté dans le menu des exercices. C'est fonctionnel donc on doit pouvoir merger...

Fusionner la branche 

---

src/exercices/3e/3G13.js

D'où la nécessité de nommer correctement les variables :
typesDeQuestionsDisponibles
et typesQuestionsDisponiblesNumbers

un labsus entre typesQuestionsDisponibles et typesDeQuestionsDisponibles

---

src/components/Diaporama.svelte
src/components/Eleve.svelte
src/components/exercice/ExerciceVueEleve.svelte
src/components/exercice/HeaderExerciceVueEleve.svelte
src/components/forms/ButtonToggle.svelte
src/components/store.ts

Adaptation au redimensionnement plus robuste
Bouton refresh
Repositionnement du bouton voir/masquer correction
Fonte light
Numérotation pour les titres
Scores

Améliorations de la vue élève

---

src/components/exercice/ExerciceMathalea.svelte
src/components/exercice/ExerciceVueEleve.svelte

Texte et solution sur une colonne
Problème des IDs identiques

Pb colonnes

---

src/components/Start.svelte
src/components/store.ts

Passé la variable responsable dans le store
Commenté les lignes 72 à 84 dans `Start` (voir fil **Slack** à ce sujet)

Comportement du menu de choix des exos

---

src/app.css
src/components/Eleve.svelte
src/components/Footer.svelte
src/components/Start.svelte
src/components/exercice/ExerciceMathalea.svelte
src/components/exercice/ExerciceVueEleve.svelte

* __Positionnement des aides différentes__ en haut et au milieu de chaque exercices/questions pour un affichage visible tout le temps, même en mobile
* __Plein écran__ : correction (non satisfaisante -> voir Slack) du bouton Plein écran

Petites réparations

---

src/app.css

Positionnement des aides au centre de l'écran

Position des aides

---

src/components/exercice/ExerciceStatic.svelte

* Positionnement après la consigne
* Utilisation du même style que pour les exercices dynamiques

Correction annales

---

src/components/exercice/Settings.svelte
src/components/sidebar/EntreeListeExos.svelte

* Position sous le bouton info dans le menu
* Visualisation avec un clic

Positionnement Comment

---

src/components/sidebar/EntreeRecherche.svelte
src/components/sidebar/NiveauListeExos.svelte
src/components/sidebar/SearchExercice.svelte

* Implémentation des mêmes boutons dans la liste des exercices affichés lors d'une recherche que dans la liste usuelle.
* Prise en compte d'une liste vide pour _Nouveautés_ (affichage message).

Liste Recherche + Nouveautés

---

src/components/Diaporama.svelte
src/components/forms/ButtonToggle.svelte
src/components/store.ts

Implémentation d'un nouveau type de défilement des diapos : question dans le temps prévu puis correction sur pause. Le bouton _lecture_ (ou _suivant_ ) permet de relancer le diaporama.

Mode Question puis Correction

---

src/components/Eleve.svelte
src/components/exercice/ExerciceMathalea.svelte
src/components/exercice/ExerciceStatic.svelte
src/components/exercice/ExerciceVueEleve.svelte

* Changement de couleur et de style
* retrait des styles sur les marges haute et basse

Bandeau correction

---

src/components/Diaporama.svelte
src/components/store.ts

Possibilité d'afficher la question __et__ la réponse dans le mode Question _puis_ Correction

Q+C dans mode Q puis C

---

src/components/Can.svelte

* Boutons de Zoom
* Utilisation de grille pour la mise en page afin d'utiliser toute la largeur de la page
* Uniformisation des bandeaux pour la correction

Améliorations Vue CAN

---

src/components/Latex.svelte

Possibilité de téléverser code LaTeX et images en un clic !

Utilisation d'Overleaf

---

src/components/Eleve.svelte
src/components/Latex.svelte
src/components/exercice/HeaderExerciceVueEleve.svelte

* position des consignes+correction dans vue élève
* titres des exercices inconsistant dans vue élève
* gestion des noms de fichiers images sans extension pour export LaTeX

Correction de bugs
